language: python

python:
  - '2.6'
  - '2.7'
  - '3.3'
  - pypy

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq subversion mercurial bazaar


install:
  - pip install -e . --use-mirrors

script:
  - python setup.py test

notifications:
  email:
    recipients:
      - jakub@opbeat.com
